//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.28 at 12:04:05 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "rest.mule.whitehorses.nl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.whitehorses.mule.rest;
