package nl.whitehorses.mulewb.services.cityservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-28T21:16:38.998+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://services.mulewb.whitehorses.nl/CityService", name = "FindAllCities")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FindAllCities {

    @WebMethod
    @WebResult(name = "CityServiceResponse", targetNamespace = "http://services.mulewb.whitehorses.nl/CityService", partName = "out")
    public CityServiceResponse findAllCities(
        @WebParam(partName = "in", name = "CityServiceRequest", targetNamespace = "http://services.mulewb.whitehorses.nl/CityService")
        java.lang.Object in
    );
}
